### ISSUE TITLE
Discord doesn't start after installation

### ISSUE THREAD

**Issue by JKakaofanatiker** [AryToNeX/Glasscord#51]
I also tried to start it via terminal.
Output:
```
[jan@gaming-tux-manjaro resources]$ discord 
You are running a packaged Glasscord installation!
Fetching featured Glasscord modules for application: discord
[Glasscord] [Linux] Module loaded!
[Glasscord] [DiscordTitlebar] Module loaded!
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module '/opt/discord/resources/app/app_bootstrap/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7646:16)
    at Function.Module._resolveFilename (/opt/discord/resources/app/glasscord.asar/src/index.js:97:29)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at injectFromResources (/opt/discord/resources/app/glasscord.asar/src/index.js:90:9)
    at Object.<anonymous> (/opt/discord/resources/app/glasscord.asar/src/index.js:53:2)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
[Glasscord Featured Modules] Matching files for featured/discord/discord_titlebar.js.
```
Nothing happens after the last output.

**Comment by AryToNeX** [comment]
This means that you did not install the module correctly; thus it is not a bug. Please review your installation steps, and mind that modifying a Discord installation in `/opt/` will break it when it updates. I hugely recommend you to play around with Glasscord on a local Discord installation, preferably under the home directory so it's easily accessible.
